language: python
python:
    - "2.7"
install:
    - pip install requests junit_xml beaker-client mock
    - pip install pylint pycodestyle
script:
    - python -m unittest discover tests
    - pylint tests
    - pycodestyle .
    - pip install .
    - pip uninstall -y skt
